# 安装

`pip install numpy`

# 创建ndarray

In [1]:
import numpy as np
# 创建一维数组
a = np.array([1, 2, 3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [2]:
# 创建多维数组
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print(type(b))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [3]:
# 设置数组元素类型
# 创建一维数组
c = np.array([1, 2, 3], dtype='complex')
print(c)
print(type(c))

[1.+0.j 2.+0.j 3.+0.j]
<class 'numpy.ndarray'>


In [4]:
# 查看数组维度
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
1


In [11]:
# 转置
d = np.array([[1, 2], [3, 4], [5, 6]])
print(d.shape, d.size, d.ndim)
e = d.reshape(d.shape[1], d.shape[0])
print(d)
print(e)

(3, 2) 6 2
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [12]:
# dtype对象
t1 = np.dtype(np.int64)
print(t1)

int64
